---
title: Identification of vaccine effects when exposure status is unknown
author:
  - name: Mats J. Stensrud
  - name: Louisa H. Smith
date: '2023-03-01'
output:
  distill::distill_article:
    self_contained: false
journal: 
  title: "Epidemiology"
volume: 34
issue: 2
doi: "10.1097/ede.0000000000001573"
citation_url: "https://journals.lww.com/epidem/Fulltext/2023/03000/Identification_of_Vaccine_Effects_When_Exposure.8.aspx"
categories: Epidemiology
---

```{r, echo = FALSE}
distilltools::icon_link(
  icon = "doi",
  text = "Online version",
  url = "https://journals.lww.com/epidem/Fulltext/2023/03000/Identification_of_Vaccine_Effects_When_Exposure.8.aspx"
)
# 
# distilltools::icon_link(
#   icon = "fas fa-file-pdf",
#   text = "PDF",
#   url = ""
# )
# 
distilltools::icon_link(
  icon = "arxiv",
  text = "Pre-print",
  url = "https://arxiv.org/abs/2111.11548"
)
# 
# distilltools::icon_link(
#   icon = "fab fa-github",
#   text = "Code",
#   url = ""
# )
```

# Abstract

Results from randomized controlled trials (RCTs) help determine vaccination strategies and related public health policies. However, defining and identifying estimands that can guide policies in infectious disease settings is difficult, even in an RCT. The effects of vaccination critically depend on characteristics of the population of interest, such as the prevalence of infection, the number of vaccinated, and social behaviors. To mitigate the dependence on such characteristics, estimands, and study designs, that require conditioning or intervening on exposure to the infectious agent have been advocated. But a fundamental problem for both RCTs and observational studies is that exposure status is often unavailable or difficult to measure, which has made it impossible to apply existing methodology to study vaccine effects that account for exposure status. In this work, we present new results on this type of vaccine effects. Under plausible conditions, we show that point identification of certain relative effects is possible even when the exposure status is unknown. Furthermore, we derive sharp bounds on the corresponding absolute effects. We apply these results to estimate the effects of the ChAdOx1 nCoV-19 vaccine on SARS-CoV-2 disease (COVID-19) conditional on post-vaccine exposure to the virus, using data from a large RCT.

