project:
  type: website
  resources:
  - "files/louisahsmith_cv.pdf"
website:
  title: "Louisa H. Smith"
  site-url: "https://louisahsmith.com"
  navbar:
    search: false
    left:
      - href: about.qmd
      - href: publications.qmd
      - href: talks.qmd
      - href: teaching.qmd
      # - text: "Posts"
      #   href: blog.qmd
      # - text: "Teaching"
      #   href: teaching.qmd
      # - text: "Projects"
      #   href: projects.qmd
    right:
      - text: CV
        href: files/cv_louisahsmith.pdf
  open-graph: true
format:
  html:
    theme:
      - yeti
      - custom.scss
  
execute: 
  echo: false
  message: false
  warning: false
  freeze: auto