---
title: Teaching
---

### Northeastern University

#### PHTH 2210: Foundations of Biostatistics

Co-instructor (fall 2024)

*Undergraduate course introducing basic statistical concepts and methods for public health and health sciences students.*

#### PHTH 6800: Causal Inference in Public Health Research

Instructor (spring 2023, 2024)

*PhD course introducing potential outcomes, causal graphs, g-formula, marginal structural models, quasi-experimental methods, and more.*

### Emory University Rollins School of Public Health

#### [EPI590R: R Bootcamp](https://epi590r.louisahsmith.com/)

Instructor (summer 2023, 2024)

*Best practices and tools for data management, tables and figures, and reproducible research in R.*

### Harvard TH Chan School of Public Health

#### [ID543: Intro to R](https://id543.louisahsmith.com)

Instructor (summer 2023, 2024)

*Introduction to R for MPH students.*

#### EPI 207: Advanced Epidemiologic Methods

(Head) Teaching fellow (fall 2018, fall 2019, fall 2020)

*Causal inference for time-varying exposures: g-formula, marginal structural models, g-estimation of structural nested models; static and dynamic treatment regimes.*

#### BST 256: Theories and Methods for Causality I

Teaching fellow (fall 2020)

*Structural causal models, graphical models, algorithms for identification.*

#### [Introduction to R](https://intro-to-R-2020.louisahsmith.com)

Instructor (fall 2019, summer 2020)

*Developed and taught short course to introduce R to graduate students. Topics included creating figures and tables, cleaning data, writing functions.*

#### Introduction to Epidemiology

Co-instructor (summer 2019, summer 2020)

*Epidemiology course for participants in the Harvard Summer Program in Biostatistics & Computational Biology.*

#### PHS 2000: Quantitative Research Methods in Population Health Sciences

Teaching fellow (fall 2017, spring 2018, fall 2019)

*Regression models, sampling, longitudinal and multilevel analysis, time-varying confounding, mediation and interaction, econometric methods, missing data.*

### University of California, Berkeley

#### PH 150A: Introduction to Epidemiology and Human Disease

Graduate student instructor (spring 2016)

*Basic epidemiologic methods, overview of epidemiology of diseases/conditions of public health importance for undergraduates.*

#### PH 250A: Epidemiologic Methods

Graduate student instructor (fall 2015)

*Study design, sampling, data collection, analysis, inference for MPH students.*
