---
title: "International Registry of Coronavirus Exposure in Pregnancy (IRCEP) — Cohort description and methodological considerations"
description: "We describe a pregnancy cohort recruited and followed during the COVID-19 pandemic, as well as some challenges encountered during the process."
author:
  - name: Sonia Hernández-Díaz
  - name: Louisa H. Smith
  - name: Camille Dollinger
  - name: Enrique F. Schisterman
  - name: Rino Bellocco
  - name: Diego F. Wyszynski
output:
  distill::distill_article:
    self_contained: false
date: "2022-06-01"
categories: "American Journal of Epidemiology"
journal: 
  title: "American Journal of Epidemiology"
volume: 191
issue: 6
citation_url: "https://doi.org/10.1093/aje/kwac046"
---


```{r, echo = FALSE}
distilltools::icon_link(
  icon = "doi",
  text = "Online version",
  url = "https://doi.org/10.1093/aje/kwac046"
)
# 
# distilltools::icon_link(
#   icon = "fas fa-file-pdf",
#   text = "PDF",
#   url = ""
# )
# 
# distilltools::icon_link(
#   icon = "arxiv",
#   text = "Pre-print",
#   url = ""
# )
# 
# distilltools::icon_link(
#   icon = "fab fa-github",
#   text = "Code",
#   url = ""
# )
```

# Abstract

Limited data are available about the potential health effects of infection with the severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2) on pregnant women and their developing offspring. We developed the International Registry of Coronavirus Exposure in Pregnancy (IRCEP) to provide data on the risk of major adverse obstetric and neonatal outcomes among women with varying degrees of severity and timing of COVID-19 exposure during pregnancy. We describe here the cohort and share the lessons learned. The IRCEP enrolls women tested for SARS-CoV-2 or with a clinical diagnosis of COVID-19 during pregnancy regardless of SARS-CoV-2 test results and obtains information using an online data collection system. By the end of March 2021, 17,532 participants from 77 countries had enrolled; 54% enrolled during pregnancy and 46% afterwards. Among women with symptomatic COVID-19 with a positive SARS-CoV-2 test (N=4,934), symptoms were mild in 41%, moderate in 52% and severe in 7%; 7.7% were hospitalized for COVID-19 and 1.7% were admitted to an intensive care unit. The key practical challenge has been retention of the large number of participants enrolled during pregnancy through social media. The biggest methodological challenge has been the potential bias introduced when participants enroll after pregnancy outcomes are known. Multiple biases need to be considered when estimating and interpreting the effects of COVID-19 in pregnancy in these types of cohorts. 
