---
title: "Maternal prepregnancy weight and children's behavioral and emotional outcomes"
author:
  - name: Julianna Deardorff
    affiliation: UC Berkeley
  - name: Louisa H. Smith
  - name: Lucia Petito
  - name: Hyunju Kim
  - name: Barbara F. Abrams
date: '2017-10-01'
output:
  distill::distill_article:
    self_contained: false
journal: 
  title: "American Journal of Preventive Medicine"
volume: 53
issue: 4
doi: "10.1016/j.amepre.2017.05.013"
citation_url: "https://doi.org/10.1016/j.amepre.2017.05.013"
categories: "American Journal of Preventive Medicine"
---

```{r, echo = FALSE}
distilltools::icon_link(
  icon = "doi",
  text = "Online version",
  url = "https://doi.org/10.1016/j.amepre.2017.05.013"
)
# 
# distilltools::icon_link(
#   icon = "fas fa-file-pdf",
#   text = "PDF",
#   url = ""
# )
# 
# distilltools::icon_link(
#   icon = "arxiv",
#   text = "Pre-print",
#   url = ""
# )
# 
# distilltools::icon_link(
#   icon = "fab fa-github",
#   text = "Code",
#   url = ""
# )
```

# Abstract


## Introduction

This study investigated associations between maternal prepregnancy BMI and child behaviors at ages 9–11 years and examine interaction by race and gender.

## Methods

The National Longitudinal Survey of Youth and the Children and Young Adults surveys are U.S.-based, ongoing longitudinal studies, initiated in 1979 and 1986, respectively. Mothers (n=2,952) reported pregnancy and child (n=5,660) developmental information at multiple time points. Child total, internalizing, and externalizing problems at ages 9–11 years were assessed using the Behavior Problems Index (BPI), collected biennially until 2012. Associations between prepregnancy BMI and child BPI outcomes were examined, as well as two- and three-way interactions by race and gender. Analyses were conducted in 2017.

## Results

Boys whose mothers had higher prepregnancy weights exhibited higher total BPI and externalizing scores at ages 9–11 years versus those with normal-weight mothers. Boys with severely obese mothers had higher total BPI (mean difference=7.99, 95% CI=3.53, 12.46) and externalizing (mean difference=5.77, 95% CI=1.50, 10.04) scores. Prepregnancy underweight was associated with boys’ higher total BPI (mean difference=2.34, 95% CI=0.02, 4.66) and externalizing (mean difference=3.30, 95% CI=0.69, 5.91); these associations were not significant in sensitivity analyses. No associations emerged for girls or internalizing problems. Two-way interactions by race and three-way interactions by race and gender were not significant.

## Conclusions

Maternal prepregnancy weight was associated with BPI level among boys. Boys with severely obese mothers exhibited markedly higher behavioral problems at ages 9–11 years versus those with normal-weight mothers, regardless of race. Maintaining healthy prepregnancy weight may be important for preventing boys’ deleterious behavior outcomes in middle childhood.
