---
title: "Health issues in the industrial port zone of Marseille, France: The Fos EPSEAL community-based cross-sectional survey"
author:
  - name: Alison K. Cohen
  - name: Travis Richards
  - name: Barbara L. Allen
  - name: Yolaine Ferrier
  - name: Johanna Lees
  - name: Louisa H. Smith
date: '2017-11-01'
output:
  distill::distill_article:
    self_contained: false
journal: 
  title: "Journal of Public Health"
volume: 26
doi: "10.1007/s10389-017-0857-5"
citation_url: "https://doi.org/10.1007/s10389-017-0857-5"
categories: "Journal of Public Health"
---

```{r, echo = FALSE}
distilltools::icon_link(
  icon = "doi",
  text = "Online version",
  url = "https://doi.org/10.1007/s10389-017-0857-5"
)
# 
# distilltools::icon_link(
#   icon = "fas fa-file-pdf",
#   text = "PDF",
#   url = ""
# )
# 
# distilltools::icon_link(
#   icon = "arxiv",
#   text = "Pre-print",
#   url = ""
# )
# 
# distilltools::icon_link(
#   icon = "fab fa-github",
#   text = "Code",
#   url = ""
# )
```

# Abstract

**Aim:** Community-based participatory research (CBPR) is an increasingly common approach in the USA, but still relatively rare in Europe. In the industrial zone of Marseille, there is a long history of pollution, but little is known about the health implications. This study documented the prevalence of different health issues in two heavily polluted towns in the industrial zone using a CBPR approach.

**Subject and methods:** This study used a CBPR approach and epidemiologic methods to answer community members' questions about the health of residents in Marseille's industrial zone by randomly sampling a cross-section of residents to systematically document health issues in Fos-sur-Mer and Port-Saint-Louis-du-Rhône, two towns in the industrial port area of Marseille, France.

**Results:** Many chronic illnesses were elevated in these communities, as compared to regional and national prevalences, including chronic skin problems, asthma, cancer, and diabetes. Chronic skin problems and asthma were among the most common chronic illnesses reported. A majority of respondents also reported acute symptoms that affected daily life, including eye irritation or nose and throat problems.

**Conclusion:** There is likely an environmental explanation for why, even after direct standardization, the prevalences of many diseases were higher in these communities than elsewhere. The combination of CBPR and rigorous epidemiologic methods helps make our findings relevant to both community members and researchers.
