---
title: "Timing and severity of COVID-19 during pregnancy and the risk of preterm birth in the International Registry of Coronavirus Exposure in Pregnancy"
author:
  - name: Louisa H. Smith
  - name: Camille Dollinger
  - name: Tyler J. VanderWeele
  - name: Diego F. Wyszynski
  - name: Sonia Hernández-Díaz
date: '2022-09-01'
output:
  distill::distill_article:
    self_contained: false
journal: 
  title: "BMC Pregnancy & Childbirth"
volume: 22
# issue: 
doi: "10.1186/s12884-022-05101-3"
citation_url: "https://bmcpregnancychildbirth.biomedcentral.com/articles/10.1186/s12884-022-05101-3"
categories: "BMC Pregnancy & Childbirth"
---

```{r, echo = FALSE}
distilltools::icon_link(
  icon = "doi",
  text = "Online version",
  url = "https://bmcpregnancychildbirth.biomedcentral.com/articles/10.1186/s12884-022-05101-3"
)
# 
# distilltools::icon_link(
#   icon = "fas fa-file-pdf",
#   text = "PDF",
#   url = ""
# )
# 
# distilltools::icon_link(
#   icon = "arxiv",
#   text = "Pre-print",
#   url = ""
# )
# 
# distilltools::icon_link(
#   icon = "fab fa-github",
#   text = "Code",
#   url = ""
# )
```

# Abstract

**Background**: Studies of preterm delivery after COVID-19 are often subject to selection bias and do not distinguish between early vs. late infection in pregnancy, nor between spontaneous vs. medically indicated preterm delivery. This study aimed to estimate the risk of preterm birth (overall, spontaneous, and indicated) after COVID-19 during pregnancy, while considering different levels of disease severity and timing.

**Methods**: Pregnant and recently pregnant people who were tested for or clinically diagnosed with COVID-19 during pregnancy enrolled in an international internet-based cohort study between June 2020 and July 2021. We used several analytic approaches to minimize confounding and immortal time bias, including multivariable regression, time-to-delivery models, and a case-time-control design. 

**Results**: Among 14 264 eligible participants from 70 countries who did not report a pregnancy loss before 20 gestational weeks, 5893 had completed their pregnancies and reported delivery information; others were censored at time of their last follow-up. Participants with symptomatic COVID-19 before 20 weeks’ gestation had no increased risk of preterm delivery compared to those testing negative, with adjusted risks of 10.0% (95% CI 7.8, 12.0) vs. 9.8% (9.1, 10.5). Mild COVID-19 later in pregnancy was not clearly associated with preterm delivery. In contrast, severe COVID-19 after 20 weeks’ gestation led to an increase in preterm delivery compared to milder disease. For example, the risk ratio for preterm delivery comparing severe to mild/moderate COVID-19 at 35 weeks was 2.8 (2.0, 4.0); corresponding risk ratios for indicated and spontaneous preterm delivery were 3.7 (2.0, 7.0) and 2.3 (1.2, 3.9), respectively.

**Conclusions**: Severe COVID-19 late in pregnancy sharply increased the risk of preterm delivery compared to no COVID-19. This elevated risk was primarily due to an increase in medically indicated preterm deliveries, included preterm cesarean sections, although an increase in spontaneous preterm delivery was also observed. In contrast, mild or moderate COVID-19 conferred minimal risk, as did severe disease early in pregnancy. 
