---
title: Bounding bias due to selection
description: "We provide bounds for selection bias under a variety of situations."
author:
  - name: Louisa H. Smith
    affiliation: Harvard TH Chan School of Public Health
  - name: Tyler VanderWeele
date: '2019-07-01'
output:
  distill::distill_article:
    self_contained: false
journal: 
  title: "Epidemiology"
volume: 30
issue: 4
doi: "10.1097/EDE.0000000000001032"
citation_url: "https://doi.org/10.1097/EDE.0000000000001032"
categories: Epidemiology
---

```{r, echo = FALSE}
distilltools::icon_link(
  icon = "doi",
  text = "Online version",
  url = "https://doi.org/10.1097/EDE.0000000000001032"
)
# 
distilltools::icon_link(
  icon = "fas fa-file-pdf",
  text = "PDF",
  url = "bounding-bias-due-to-selection.pdf"
)

distilltools::icon_link(
  icon = "fas fa-file-pdf",
  text = "Online appendix",
  url = "https://download.lww.com/wolterskluwer_vitalstream_com/PermaLink/EDE/B/EDE_2019_04_12_SMITH_EDE18-0514R2_SDC1.pdf"
)

distilltools::icon_link(
  icon = "fas fa-calculator",
  text = "Online calculator",
  url = "http://selection-bias.louisahsmith.com"
)

distilltools::icon_link(
  icon = "fab fa-r-project",
  text = "R package",
  url = "https://cran.r-project.org/web/packages/EValue/index.html"
)
               
```

# Abstract

When epidemiologic studies are conducted in a subset of the population, selection bias can threaten the validity of causal inference. This bias can occur whether or not that selected population is the target population and can occur even in the absence of exposure–outcome confounding. However, it is often difficult to quantify the extent of selection bias, and sensitivity analysis can be challenging to undertake and to understand. In this article, we demonstrate that the magnitude of the bias due to selection can be bounded by simple expressions defined by parameters characterizing the relationships between unmeasured factor(s) responsible for the bias and the measured variables. No functional form assumptions are necessary about those unmeasured factors. Using knowledge about the selection mechanism, researchers can account for the possible extent of selection bias by specifying the size of the parameters in the bounds. We also show that the bounds, which differ depending on the target population, result in summary measures that can be used to calculate the minimum magnitude of the parameters required to shift a risk ratio to the null. The summary measure can be used to determine the overall strength of selection that would be necessary to explain away a result. We then show that the bounds and summary measures can be simplified in certain contexts or with certain assumptions. Using examples with varying selection mechanisms, we also demonstrate how researchers can implement these simple sensitivity analyses.
