---
title: "Multiple-bias sensitivity analysis using bounds"
description: "We show that it is possible to bound the total composite bias due to unmeasured confounding, selection, and differential misclassification, and to use that bound to assess the sensitivity of a risk ratio to any combination of these biases."
author:
  - name: Louisa H. Smith
    affiliation: Harvard TH Chan School of Public Health
  - name: Maya B. Mathur
    url: www.mayamathur.com
    affiliation: Stanford University
  - name: Tyler J. VanderWeele
    affiliation: Harvard TH Chan School of Public Health
    url: https://www.hsph.harvard.edu/tyler-vanderweele/
date: 2021-09-01
output:
  distill::distill_article:
    self_contained: false
journal: 
  title: "Epidemiology"
volume: 32
issue: 5
citation_url: "https://doi.org/10.1097/EDE.0000000000001380"
categories: Epidemiology
---

```{r, echo = FALSE}
distilltools::icon_link(
  icon = "doi",
  text = "Online version",
  url = "https://doi.org/10.1097/EDE.0000000000001380"
)
# 
distilltools::icon_link(
  icon = "fas fa-file-pdf",
  text = "PDF",
  url = "multiple-bias-sensitivity-analysis-using-bounds.pdf"
)

distilltools::icon_link(
  icon = "fas fa-file-pdf",
  text = "Online appendix",
  url = "https://cdn-links.lww.com/permalink/ede/b/ede_2021_05_31_smith_ede20-0315_sdc1.pdf"
)
```

# Abstract

Confounding, selection bias, and measurement error are well-known sources of bias in epidemiologic research. Methods for assessing these biases have their own limitations. Many quantitative sensitivity analysis approaches consider each type of bias individually, while more complex approaches are harder to implement or require numerous assumptions. By failing to consider multiple biases at once, researchers can underestimate or overestimate their joint impact. We show that it is possible to bound the total composite bias due to these three sources, and to use that bound to assess the sensitivity of a risk ratio to any combination of these biases. We derive bounds for the total composite bias under a variety of scenarios, providing researchers with tools to assess their total potential impact. We apply this technique to a study where unmeasured confounding and selection bias are both concerns, and to another study in which possible differential exposure misclassification and confounding are concerns. The approach we describe, though conservative, is easier to implement and makes simpler assumptions than quantitative bias analysis. We provide R functions to aid implementation.
